// npcs.js — NPC definitions for Life RPG
//
// Each NPC offers a roster of quests. When a player accepts an NPC quest,
// XP is calculated using the standard formula but multiplied by the NPC's
// xpMultiplier (1.5 by default) as a bonus for stepping outside comfort zones.
//
// Quest fields map directly to the addTask() interface:
//   title           → task name
//   description     → shown in the quest offer card
//   category        → maps to an existing category id in data.js
//   duration        → 1–5 (feeds into XP formula: duration × 10)
//   difficulty      → 1–5 (feeds into XP formula: difficulty × 12)
//   uncomfortability→ 1–5 (feeds into XP formula: uncomfortability × 15)

const NPCS = [

  // ── 1. Gary the Gym Rat ─────────────────────────────────────────────────
  {
    id:          'gary',
    name:        'Gary the Gym Rat',
    tagline:     '"No days off. No excuses. Let\'s get it."',
    avatar:      '🏋️',
    personality: 'aggressive-motivational',
    xpMultiplier: 1.5,
    quests: [
      {
        id:               'gary_pushups',
        title:            'Do 50 Push-Ups',
        description:      '50 reps, chest to floor, no cheating. Gary is watching.',
        category:         'body_health',
        duration:         1,
        difficulty:       4,
        uncomfortability: 3,
      },
      {
        id:               'gary_plank',
        title:            'Hold a Plank for 2 Minutes',
        description:      'Two minutes. Straight back. Core tight. Don\'t you dare drop.',
        category:         'body_health',
        duration:         1,
        difficulty:       3,
        uncomfortability: 4,
      },
      {
        id:               'gary_jumping_jacks',
        title:            'Do 100 Jumping Jacks',
        description:      'Full extension every rep. Gary counts the half-reps as misses.',
        category:         'body_health',
        duration:         1,
        difficulty:       2,
        uncomfortability: 2,
      },
      {
        id:               'gary_steps',
        title:            'Walk 10,000 Steps Today',
        description:      'Get moving. No excuses about weather. Walk it out.',
        category:         'body_health',
        duration:         4,
        difficulty:       2,
        uncomfortability: 1,
      },
      {
        id:               'gary_burpees',
        title:            'Do 20 Burpees',
        description:      'The king of all exercises. Gary\'s doing them too. Probably.',
        category:         'body_health',
        duration:         1,
        difficulty:       4,
        uncomfortability: 4,
      },
      {
        id:               'gary_wall_sit',
        title:            'Hold a Wall Sit for 90 Seconds',
        description:      'Back flat, thighs parallel. This is character building.',
        category:         'body_health',
        duration:         1,
        difficulty:       3,
        uncomfortability: 3,
      },
      {
        id:               'gary_run',
        title:            'Run 5km Without Stopping',
        description:      'Pace doesn\'t matter. Stopping does. Don\'t stop.',
        category:         'body_health',
        duration:         3,
        difficulty:       4,
        uncomfortability: 3,
      },
      {
        id:               'gary_circuit',
        title:            'Complete a Full Bodyweight Circuit',
        description:      'Squats, lunges, push-ups, sit-ups — go through the full lot twice.',
        category:         'body_health',
        duration:         2,
        difficulty:       4,
        uncomfortability: 3,
      },
    ],
  },

  // ── 2. Mei the Monk ─────────────────────────────────────────────────────
  {
    id:          'mei',
    name:        'Mei the Monk',
    tagline:     '"Stillness is not emptiness. It is everything."',
    avatar:      '🧘',
    personality: 'calm-philosophical',
    xpMultiplier: 1.5,
    quests: [
      {
        id:               'mei_meditate',
        title:            'Meditate for 10 Minutes',
        description:      'Find a quiet place. Breathe. Let thoughts pass like clouds.',
        category:         'body_health',
        duration:         1,
        difficulty:       2,
        uncomfortability: 2,
      },
      {
        id:               'mei_gratitude',
        title:            'Write 3 Things You\'re Grateful For',
        description:      'Not generic ones. Specific, felt gratitude from your day.',
        category:         'body_health',
        duration:         1,
        difficulty:       1,
        uncomfortability: 1,
      },
      {
        id:               'mei_silence',
        title:            'Sit in Silence for 5 Minutes',
        description:      'No phone. No music. Just you and the present moment.',
        category:         'body_health',
        duration:         1,
        difficulty:       2,
        uncomfortability: 3,
      },
      {
        id:               'mei_mindful_walk',
        title:            'Go for a Mindful Walk With No Phone',
        description:      'Leave it behind. Observe everything. Rush nothing.',
        category:         'body_health',
        duration:         2,
        difficulty:       2,
        uncomfortability: 2,
      },
      {
        id:               'mei_journal',
        title:            'Journal Your Thoughts for 10 Minutes',
        description:      'Stream of consciousness. No filter. Just write.',
        category:         'mind_learning',
        duration:         1,
        difficulty:       1,
        uncomfortability: 2,
      },
      {
        id:               'mei_breathe',
        title:            'Practice Deep Breathing for 5 Minutes',
        description:      '4 counts in, hold 4, out 4. Repeat until calm settles.',
        category:         'body_health',
        duration:         1,
        difficulty:       1,
        uncomfortability: 1,
      },
      {
        id:               'mei_detox',
        title:            'Full Digital Detox for 2 Hours',
        description:      'No screens of any kind. Exist in the analogue world.',
        category:         'body_health',
        duration:         2,
        difficulty:       3,
        uncomfortability: 4,
      },
      {
        id:               'mei_future_letter',
        title:            'Write a Letter to Your Future Self',
        description:      'One year from now. What do you hope they know? What do you fear?',
        category:         'mind_learning',
        duration:         2,
        difficulty:       2,
        uncomfortability: 3,
      },
    ],
  },

  // ── 3. Derek the Life Admin Demon ───────────────────────────────────────
  {
    id:          'derek',
    name:        'Derek the Life Admin Demon',
    tagline:     '"You\'ve been avoiding this. I haven\'t."',
    avatar:      '👿',
    personality: 'chaotic-productive',
    xpMultiplier: 1.5,
    quests: [
      {
        id:               'derek_clean_area',
        title:            'Clean One Area of Your Home',
        description:      'Pick the worst corner. You know which one. Deal with it.',
        category:         'life_admin',
        duration:         2,
        difficulty:       2,
        uncomfortability: 2,
      },
      {
        id:               'derek_emails',
        title:            'Reply to 3 Emails You\'ve Been Ignoring',
        description:      'They\'re not going away on their own. Derek checked.',
        category:         'life_admin',
        duration:         1,
        difficulty:       2,
        uncomfortability: 3,
      },
      {
        id:               'derek_delete_photos',
        title:            'Delete 50 Photos From Your Phone',
        description:      'Blurry ones. Duplicates. Screenshots of things you never did.',
        category:         'life_admin',
        duration:         1,
        difficulty:       1,
        uncomfortability: 1,
      },
      {
        id:               'derek_desktop',
        title:            'Organise Your Desktop',
        description:      'Files in folders. Shortcuts deleted. A clean digital slate.',
        category:         'life_admin',
        duration:         1,
        difficulty:       1,
        uncomfortability: 1,
      },
      {
        id:               'derek_subscription',
        title:            'Cancel a Subscription You Don\'t Use',
        description:      'You know it\'s there. You\'ve known for months. Cancel it.',
        category:         'finance',
        duration:         1,
        difficulty:       2,
        uncomfortability: 2,
      },
      {
        id:               'derek_documents',
        title:            'File or Shred Old Documents',
        description:      'That pile of paper that\'s been breeding on your desk. Handle it.',
        category:         'life_admin',
        duration:         2,
        difficulty:       1,
        uncomfortability: 1,
      },
      {
        id:               'derek_inbox',
        title:            'Get Your Email Inbox Below 10 Unread',
        description:      'Archive, delete, reply. Ruthlessly. Derek will not accept excuses.',
        category:         'life_admin',
        duration:         2,
        difficulty:       2,
        uncomfortability: 2,
      },
      {
        id:               'derek_appointment',
        title:            'Book an Appointment You\'ve Been Putting Off',
        description:      'Doctor. Dentist. Accountant. You know what it is.',
        category:         'life_admin',
        duration:         1,
        difficulty:       2,
        uncomfortability: 3,
      },
    ],
  },

  // ── 4. Brenda the Socialite ──────────────────────────────────────────────
  {
    id:          'brenda',
    name:        'Brenda the Socialite',
    tagline:     '"Life is better shared. Go on, reach out!"',
    avatar:      '🥂',
    personality: 'warm-extroverted',
    xpMultiplier: 1.5,
    quests: [
      {
        id:               'brenda_smile',
        title:            'Smile at 5 Strangers',
        description:      'Genuine smiles. Not the weird ones. Brenda believes in you.',
        category:         'social_relationships',
        duration:         1,
        difficulty:       1,
        uncomfortability: 2,
      },
      {
        id:               'brenda_old_contact',
        title:            'Text Someone You Haven\'t Spoken to in Months',
        description:      'That person you keep thinking about. Message them. Now.',
        category:         'social_relationships',
        duration:         1,
        difficulty:       2,
        uncomfortability: 3,
      },
      {
        id:               'brenda_compliment',
        title:            'Pay Someone a Genuine Compliment',
        description:      'Not about appearance. Something real. Their character, their work.',
        category:         'social_relationships',
        duration:         1,
        difficulty:       2,
        uncomfortability: 3,
      },
      {
        id:               'brenda_kindness',
        title:            'Do a Random Act of Kindness',
        description:      'Unannounced. Unexpected. Just because you can.',
        category:         'social_relationships',
        duration:         1,
        difficulty:       1,
        uncomfortability: 2,
      },
      {
        id:               'brenda_family',
        title:            'Call a Family Member',
        description:      'A real phone call. Not a message. Voice and everything.',
        category:         'social_relationships',
        duration:         1,
        difficulty:       1,
        uncomfortability: 2,
      },
      {
        id:               'brenda_introduce',
        title:            'Introduce Yourself to Someone New',
        description:      'At work, at the gym, anywhere. First step: say your name.',
        category:         'social_relationships',
        duration:         1,
        difficulty:       3,
        uncomfortability: 4,
      },
      {
        id:               'brenda_event',
        title:            'Organise a Social Event',
        description:      'Something small is fine. The pub, a walk, a dinner. Just plan it.',
        category:         'social_relationships',
        duration:         3,
        difficulty:       3,
        uncomfortability: 3,
      },
      {
        id:               'brenda_thankyou',
        title:            'Write a Heartfelt Thank-You Message',
        description:      'To someone who deserves it but probably hasn\'t heard it recently.',
        category:         'social_relationships',
        duration:         1,
        difficulty:       2,
        uncomfortability: 2,
      },
    ],
  },

  // ── 5. Professor Quill ───────────────────────────────────────────────────
  {
    id:          'quill',
    name:        'Professor Quill',
    tagline:     '"Every idle hour is a wasted lecture. Open your mind!"',
    avatar:      '🎓',
    personality: 'eccentric-academic',
    xpMultiplier: 1.5,
    quests: [
      {
        id:               'quill_read',
        title:            'Read for 20 Minutes',
        description:      'A book. A long article. Anything with depth. No scrolling counts.',
        category:         'mind_learning',
        duration:         1,
        difficulty:       1,
        uncomfortability: 1,
      },
      {
        id:               'quill_words',
        title:            'Learn 5 New Words',
        description:      'Real ones. Write them down, use each in a sentence.',
        category:         'mind_learning',
        duration:         1,
        difficulty:       1,
        uncomfortability: 1,
      },
      {
        id:               'quill_documentary',
        title:            'Watch a Documentary',
        description:      'On anything you know little about. Curiosity is the curriculum.',
        category:         'mind_learning',
        duration:         3,
        difficulty:       1,
        uncomfortability: 1,
      },
      {
        id:               'quill_podcast',
        title:            'Listen to an Educational Podcast',
        description:      'One full episode. No skipping. Take notes if you\'re keen.',
        category:         'mind_learning',
        duration:         2,
        difficulty:       1,
        uncomfortability: 1,
      },
      {
        id:               'quill_research',
        title:            'Research Something You Know Nothing About',
        description:      'Pick a topic at random. Go deep for 30 minutes. Report back.',
        category:         'mind_learning',
        duration:         2,
        difficulty:       2,
        uncomfortability: 2,
      },
      {
        id:               'quill_summary',
        title:            'Write Down What You Learned Today',
        description:      'Even a paragraph. Internalise it. Teaching yourself is learning twice.',
        category:         'mind_learning',
        duration:         1,
        difficulty:       2,
        uncomfortability: 2,
      },
      {
        id:               'quill_course',
        title:            'Complete an Online Lesson or Course Module',
        description:      'YouTube, Coursera, Duolingo — one unit of structured learning.',
        category:         'mind_learning',
        duration:         3,
        difficulty:       2,
        uncomfortability: 1,
      },
      {
        id:               'quill_teach',
        title:            'Teach Someone Something You Know',
        description:      'Real teaching forces real understanding. Pick a willing victim.',
        category:         'mind_learning',
        duration:         2,
        difficulty:       3,
        uncomfortability: 3,
      },
    ],
  },

  // ── 6. Rico the Rebel ───────────────────────────────────────────────────
  {
    id:          'rico',
    name:        'Rico the Rebel',
    tagline:     '"Routine is a cage. I\'ve got bolt cutters."',
    avatar:      '🤘',
    personality: 'chaotic-adventurous',
    xpMultiplier: 1.5,
    quests: [
      {
        id:               'rico_stranger',
        title:            'Talk to a Stranger',
        description:      'A real conversation. Not just directions. Learn something about them.',
        category:         'social_relationships',
        duration:         1,
        difficulty:       3,
        uncomfortability: 4,
      },
      {
        id:               'rico_new_food',
        title:            'Try a Food You\'ve Never Eaten',
        description:      'Order something foreign, weird, or long-feared. Eat the whole thing.',
        category:         'body_health',
        duration:         1,
        difficulty:       2,
        uncomfortability: 3,
      },
      {
        id:               'rico_new_route',
        title:            'Take a Different Route Somewhere Today',
        description:      'No satnav. No habit. Get slightly lost on purpose.',
        category:         'hobbies',
        duration:         2,
        difficulty:       1,
        uncomfortability: 2,
      },
      {
        id:               'rico_spontaneous',
        title:            'Do Something Completely Spontaneous',
        description:      'Zero planning. Something you\'d normally talk yourself out of.',
        category:         'hobbies',
        duration:         2,
        difficulty:       2,
        uncomfortability: 3,
      },
      {
        id:               'rico_coffee_shop',
        title:            'Work From a Coffee Shop for an Hour',
        description:      'Leave the house. Change the scenery. Order something good.',
        category:         'career_growth',
        duration:         2,
        difficulty:       2,
        uncomfortability: 2,
      },
      {
        id:               'rico_sign_up',
        title:            'Sign Up for Something That Scares You',
        description:      'A class, an event, a challenge. Commit before you can back out.',
        category:         'hobbies',
        duration:         1,
        difficulty:       4,
        uncomfortability: 5,
      },
      {
        id:               'rico_say_yes',
        title:            'Say Yes to an Invitation You\'d Normally Decline',
        description:      'That thing you almost replied "maybe" to. Say yes. Show up.',
        category:         'social_relationships',
        duration:         3,
        difficulty:       3,
        uncomfortability: 4,
      },
      {
        id:               'rico_face_fear',
        title:            'Do Something You\'ve Been Avoiding Out of Fear',
        description:      'You know what it is. It\'s been sitting there. Today is the day.',
        category:         'body_health',
        duration:         2,
        difficulty:       4,
        uncomfortability: 5,
      },
    ],
  },

  // ── 7. Sergeant Steel ───────────────────────────────────────────────────
  {
    id:          'steel',
    name:        'Sergeant Steel',
    tagline:     '"Discipline is freedom. Now move."',
    avatar:      '🪖',
    personality: 'military-disciplined',
    xpMultiplier: 1.5,
    quests: [
      {
        id:               'steel_early_rise',
        title:            'Wake Up Before 7am and Log It',
        description:      'Up, feet on the floor, phone unlocked. No snooze. No mercy.',
        category:         'body_health',
        duration:         1,
        difficulty:       3,
        uncomfortability: 4,
      },
      {
        id:               'steel_make_bed',
        title:            'Make Your Bed First Thing',
        description:      'First task of the day. Win it. Everything follows.',
        category:         'life_admin',
        duration:         1,
        difficulty:       1,
        uncomfortability: 1,
      },
      {
        id:               'steel_cold_shower',
        title:            'Take a Cold Shower',
        description:      'All the way cold. At least 60 seconds. Breathe through it.',
        category:         'body_health',
        duration:         1,
        difficulty:       3,
        uncomfortability: 5,
      },
      {
        id:               'steel_no_social',
        title:            'No Social Media for the Rest of the Day',
        description:      'Not even a peek. Delete the apps if you have to. Sergeant\'s orders.',
        category:         'body_health',
        duration:         5,
        difficulty:       3,
        uncomfortability: 4,
      },
      {
        id:               'steel_no_junk',
        title:            'Eat No Junk Food Today',
        description:      'Nothing processed, nothing fried, nothing that comes in a packet.',
        category:         'body_health',
        duration:         5,
        difficulty:       3,
        uncomfortability: 4,
      },
      {
        id:               'steel_plan_tomorrow',
        title:            'Write Tomorrow\'s Plan Tonight',
        description:      'Tasks, priorities, time blocks. Done before midnight. No improvising.',
        category:         'life_admin',
        duration:         1,
        difficulty:       2,
        uncomfortability: 2,
      },
      {
        id:               'steel_todo',
        title:            'Complete Your To-Do List Fully',
        description:      'Every item. No carrying over. Sergeant hates a runover list.',
        category:         'career_growth',
        duration:         3,
        difficulty:       3,
        uncomfortability: 3,
      },
      {
        id:               'steel_no_complaints',
        title:            'Zero Complaints for an Entire Day',
        description:      'Not a word. Not even internally if you can manage it. Stoic mode.',
        category:         'body_health',
        duration:         5,
        difficulty:       4,
        uncomfortability: 4,
      },
    ],
  },

  // ── 8. Luna the Creative ─────────────────────────────────────────────────
  {
    id:          'luna',
    name:        'Luna the Creative',
    tagline:     '"Everything is art if you look at it right."',
    avatar:      '🌙',
    personality: 'whimsical-artistic',
    xpMultiplier: 1.5,
    quests: [
      {
        id:               'luna_draw',
        title:            'Draw Something (Even If You Can\'t Draw)',
        description:      'That\'s the point. Terrible is fine. The act is what matters.',
        category:         'creative',
        duration:         2,
        difficulty:       2,
        uncomfortability: 3,
      },
      {
        id:               'luna_poem',
        title:            'Write a Short Poem',
        description:      'Any form. Any topic. Rhymes optional. Feelings mandatory.',
        category:         'creative',
        duration:         1,
        difficulty:       2,
        uncomfortability: 3,
      },
      {
        id:               'luna_photos',
        title:            'Take 5 Interesting Photos',
        description:      'Not selfies. Things with texture, shadow, story. Make them mean something.',
        category:         'creative',
        duration:         1,
        difficulty:       1,
        uncomfortability: 2,
      },
      {
        id:               'luna_album',
        title:            'Listen to an Album Start to Finish',
        description:      'Not shuffle. Not skip. One artist\'s vision, beginning to end.',
        category:         'creative',
        duration:         3,
        difficulty:       1,
        uncomfortability: 1,
      },
      {
        id:               'luna_rearrange',
        title:            'Rearrange Something in Your Home',
        description:      'Furniture, shelves, a wall. Change the space. Change the mind.',
        category:         'creative',
        duration:         2,
        difficulty:       1,
        uncomfortability: 2,
      },
      {
        id:               'luna_story',
        title:            'Write the Opening Paragraph of a Story',
        description:      'Any genre. Any world. Just the first paragraph. Make it vivid.',
        category:         'creative',
        duration:         1,
        difficulty:       2,
        uncomfortability: 3,
      },
      {
        id:               'luna_make',
        title:            'Create Something With Your Hands',
        description:      'Cook, build, sew, sculpt — anything physical and made by you.',
        category:         'creative',
        duration:         3,
        difficulty:       2,
        uncomfortability: 2,
      },
      {
        id:               'luna_beauty',
        title:            'Find Beauty in Something Ordinary Today',
        description:      'Write it down or photograph it. The mundane hides the magnificent.',
        category:         'creative',
        duration:         1,
        difficulty:       1,
        uncomfortability: 2,
      },
    ],
  },

];

// ── Helpers ──────────────────────────────────────────────────────────────────

// Returns the NPC object for a given id, or undefined.
function getNPCById(id) {
  return NPCS.find(n => n.id === id);
}

// Calculates XP for an NPC quest using the standard formula + NPC multiplier.
// Pass the player's xpMultiplier (from data.player.xpMultiplier) as playerMult.
function calculateNPCQuestXP(quest, npc, playerMult, importance) {
  if (playerMult  === undefined) playerMult  = 1.0;
  if (importance  === undefined) importance  = 3;
  const importanceMult = 1.0 + (importance - 1) * 0.075;
  const base = (quest.duration * 10) + (quest.difficulty * 12) + (quest.uncomfortability * 15);
  return Math.round(base * playerMult * npc.xpMultiplier * importanceMult);
}
